service_id_mapping = {
    "calc_ab": {
        "Service": "AP Calculus AB Ultimate Review Packet",
        "ID": 36,
        "ThinkificCode": 668450,
        "WorksheetCodes": 2462237,
        "SampleCodes": None,
    },
    "calc_bc": {
        "Service": "AP Calculus BC Ultimate Review Packet",
        "ID": 29,
        "ThinkificCode": 669074,
        "WorksheetCodes": 2462237,
        "SampleCodes": None,
    },
    "chemistry": {
        "Service": "AP Chemistry Ultimate Review Packet",
        "ID": 24,
        "ThinkificCode": 1815868,
        "WorksheetCodes": 2462152,
        "SampleCodes": None,
    },
    "english_lang": {
        "Service": "AP English Language and Composition Ultimate Review Packet",
        "ID": 32,
        "ThinkificCode": 1755249,
        "WorksheetCodes": 2462330,
        "SampleCodes": None,
    },
    "environmental_science": {
        "Service": "AP Environmental Science Ultimate Review Packet",
        "ID": 25,
        "ThinkificCode": 1767408,
        "WorksheetCodes": 2462166,
        "SampleCodes": None,
    },
    "euro_history": {
        "Service": "AP European History Ultimate Review Packet",
        "ID": 26,
        "ThinkificCode": 1879339,
        "WorksheetCodes": 2462317,
        "SampleCodes": None,
    },
    "human_geo": {
        "Service": "AP Human Geography Ultimate Review Packet",
        "ID": 33,
        "ThinkificCode": 667705,
        "WorksheetCodes": 1375963,
        "SampleCodes": None,
    },
    "macro": {
        "Service": "AP Macroeconomics Ultimate Review Packet",
        "ID": 27,
        "ThinkificCode": 774578,
        "WorksheetCodes": 1509218,
        "SampleCodes": 772096,
    },
    "micro": {
        "Service": "AP Microeconomics Ultimate Review Packet",
        "ID": 28,
        "ThinkificCode": 774560,
        "WorksheetCodes": 1509696,
        "SampleCodes": 772096,
    },
    "pysch": {
        "Service": "AP Psychology Ultimate Review Packet",
        "ID": 31,
        "ThinkificCode": 1777461,
        "WorksheetCodes": 2462222,
        "SampleCodes": None,
    },
    "usgov": {
        "Service": "AP US Government and Politics Ultimate Review Packet",
        "ID": 40,
        "ThinkificCode": 465167,
        "WorksheetCodes": 1525086,
        "SampleCodes": 1375972,
    },
    "ushistory": {
        "Service": "AP US History Ultimate Review Packet",
        "ID": 34,
        "ThinkificCode": 903201,
        "WorksheetCodes": 1392246,
        "SampleCodes": 1375915,
    },
    "world": {
        "Service": "AP World History Ultimate Review Packet",
        "ID": 42,
        "ThinkificCode": 591502,
        "WorksheetCodes": 1392253,
        "SampleCodes": 1375958,
    },
}
